package abuild

var installArgs = []string{
	"add",
	"--allow-untrusted",
}

var (
	// APKArchs maps Go architecture names to APK architecture names.
	APKArchs = map[string]string{
		"x86_64":  "x86_64",
		"i686":    "x86",
		"aarch64": "aarch64",
		"armv7h":  "armv7h",
		"armv6h":  "armv6h",
		"any":     "all",
	}

	buildEnvironmentDeps = []string{
		"alpine-sdk",
	}
)

const pkgInfoTemplate = `# Generated by yap {{.YAPVersion}}
pkgname = {{.PkgName}}
pkgver = {{if .Epoch}}{{.Epoch}}:{{end}}{{.PkgVer}}-r{{.PkgRel}}
pkgdesc = {{.PkgDesc}}
url = {{.URL}}
builddate = {{.BuildDate}}
size = {{.InstalledSize}}
arch = {{.ArchComputed}}
{{- if .License}}
{{ range .License }}license = {{ . }}
{{ end }}
{{- end }}
{{- if .Depends}}
{{ range .Depends }}depend = {{ . }}
{{ end }}
{{- end }}
{{- if .DataHash}}
datahash = {{.DataHash}}
{{- end }}
`
