package nfpm_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	yaperrors "github.com/M0Rf30/yap/v2/pkg/errors"
	"github.com/M0Rf30/yap/v2/pkg/nfpm"
	"github.com/M0Rf30/yap/v2/pkg/parser"
	"github.com/M0Rf30/yap/v2/pkg/pkgbuild"
)

// fixturePKGBUILDForRender returns a single-package PKGBUILD exercising
// every row of the §4 mapping table, for TestRenderYAML_RoundTrip.
func fixturePKGBUILDForRender() *pkgbuild.PKGBUILD {
	return &pkgbuild.PKGBUILD{
		PkgName:     "myapp",
		PkgBase:     "mybase",
		PkgVer:      "1.2.3~beta.1+deadbeef",
		PkgRel:      "2",
		Epoch:       "1",
		PkgDesc:     "A test application",
		Maintainer:  "Test Maintainer <test@example.com>",
		URL:         "https://example.com/myapp",
		Section:     "utils",
		Priority:    "optional",
		License:     []string{"MIT"},
		Arch:        []string{"x86_64"},
		Depends:     []string{"glibc"},
		OptDepends:  []string{"curl"},
		Suggests:    []string{"bash-completion"},
		Conflicts:   []string{"oldapp"},
		Replaces:    []string{"legacyapp"},
		Provides:    []string{"myapp-bin"},
		Breaks:      []string{"myapp (<< 1.0)"},
		PreDepends:  []string{"dpkg (>= 1.14.0)"},
		Bugs:        "https://example.com/bugs",
		DebTemplate: "debian/templates",
		DebConfig:   "debian/config",
		Group:       "Applications/System",
		Backup:      []string{"etc/myapp/config.yml"},
		PreInst:     "echo pre-install",
		PostInst:    "echo post-install",
		PreRm:       "echo pre-remove",
		PostRm:      "echo post-remove",
		PreTrans:    "echo pre-trans",
		PostTrans:   "echo post-trans",
		PreUpgrade:  "echo pre-upgrade",
		PostUpgrade: "echo post-upgrade",
		BuildDate:   1700000000,
	}
}

// renderFixtureConfig returns a Config exercising every RenderPKGBUILD row,
// rooted at testdata/render so its Scripts.* paths resolve.
func renderFixtureConfig() *nfpm.Config {
	cfg := &nfpm.Config{
		Info: nfpm.Info{
			Overridables: nfpm.Overridables{
				Depends:    []string{"glibc"},
				Recommends: []string{"curl"},
				Suggests:   []string{"bash-completion"},
				Conflicts:  []string{"oldapp"},
				Replaces:   []string{"legacyapp"},
				Provides:   []string{"myapp-bin"},
				Contents: nfpm.Contents{
					{
						Type: nfpm.TypeConfig, Source: "content/etc/myapp.conf",
						Destination: "/etc/myapp/config.yml",
						FileInfo:    &nfpm.ContentFileInfo{Mode: 0o644, Owner: "root", Group: "root"},
					},
					{
						Type: nfpm.TypeFile, Source: "content/bin/myapp", Destination: "/usr/bin/myapp",
						FileInfo: &nfpm.ContentFileInfo{Mode: 0o755, Owner: "root", Group: "root"},
					},
				},
				Scripts: nfpm.Scripts{
					PreInstall:  "scripts/preinstall.sh",
					PostInstall: "scripts/postinstall.sh",
					PreRemove:   "scripts/preremove.sh",
					PostRemove:  "scripts/postremove.sh",
				},
				RPM: nfpm.RPM{
					Scripts: nfpm.RPMScripts{
						PreTrans:  "scripts/pretrans.sh",
						PostTrans: "scripts/posttrans.sh",
					},
				},
				Deb: nfpm.Deb{
					Breaks:     []string{"myapp (<< 1.0)"},
					Predepends: []string{"dpkg (>= 1.14.0)"},
					Fields:     map[string]string{"Bugs": "https://example.com/bugs"},
				},
				APK: nfpm.APK{
					Scripts: nfpm.APKScripts{
						PreUpgrade:  "scripts/preupgrade.sh",
						PostUpgrade: "scripts/postupgrade.sh",
					},
				},
				ArchLinux: nfpm.ArchLinux{
					Scripts: nfpm.ArchLinuxScripts{
						PreUpgrade:  "scripts/preupgrade.sh",
						PostUpgrade: "scripts/postupgrade.sh",
					},
				},
			},
			Name:        "myapp",
			Arch:        "amd64",
			Platform:    "linux",
			Version:     "1.2.3",
			Prerelease:  "beta.1",
			Release:     "2",
			Epoch:       "1",
			Section:     "utils",
			Priority:    "optional",
			Maintainer:  "Test Maintainer <test@example.com>",
			Description: "A test application",
			Homepage:    "https://example.com/myapp",
			License:     "MIT",
		},
	}

	cfg.SetBaseDir("testdata/render")

	return cfg
}

func TestRenderYAML_HeaderComment(t *testing.T) {
	cfg := &nfpm.Config{Info: nfpm.Info{Name: "myapp", Version: "1.0.0"}}

	data, err := cfg.RenderYAML()
	require.NoError(t, err)

	first, _, _ := strings.Cut(string(data), "\n")
	assert.True(t, strings.HasPrefix(first, "# Generated by yap "))
	assert.True(t, strings.HasSuffix(first, " from PKGBUILD"))
}

// TestRenderYAML_RoundTrip is acceptance case (a): Parse(RenderYAML(c))
// preserves every field of a Config produced by FromPKGBUILD.
func TestRenderYAML_RoundTrip(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1700000000")

	outDir := t.TempDir()
	p := fixturePKGBUILDForRender()

	cfg, messages, err := nfpm.FromPKGBUILD(p, nfpm.FromOptions{OutputDir: outDir})
	require.NoError(t, err)
	require.Empty(t, messages)

	cfg.SetBaseDir(outDir)

	data, err := cfg.RenderYAML()
	require.NoError(t, err)

	parsed, err := nfpm.Parse(strings.NewReader(string(data)))
	require.NoError(t, err)

	assert.Equal(t, cfg.Info, parsed.Info)
	assert.Equal(t, cfg.Overrides, parsed.Overrides)
}

// TestRenderPKGBUILD_RoundTrip is acceptance case (b): RenderPKGBUILD(cfg),
// parsed by pkg/parser.ParseFile, yields a PKGBUILD whose mapped fields equal
// cfg.ToPKGBUILD(...)'s for the same packager.
func TestRenderPKGBUILD_RoundTrip(t *testing.T) {
	tests := []struct {
		name     string
		distro   string
		packager string
	}{
		{"deb", "ubuntu", nfpm.PackagerDeb},
		{"rpm", "fedora", nfpm.PackagerRPM},
		{"apk", "alpine", nfpm.PackagerAPK},
		{"archlinux", "arch", nfpm.PackagerArchLinux},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := renderFixtureConfig()

			data, _, err := cfg.RenderPKGBUILD(nil)
			require.NoError(t, err)

			dir := t.TempDir()
			require.NoError(t, os.WriteFile(filepath.Join(dir, "PKGBUILD"), data, 0o644))

			parsed, err := parser.ParseFile(tt.distro, "", dir, dir, "")
			require.NoError(t, err, "rendered PKGBUILD:\n%s", data)

			expected, _, err := cfg.ToPKGBUILD(&nfpm.ConvertOptions{
				Packager: tt.packager, Distro: tt.distro, ExpandGlobs: false,
			})
			require.NoError(t, err)

			assert.Equal(t, expected.PkgName, parsed.PkgName)
			assert.Equal(t, expected.PkgBase, parsed.PkgBase)
			assert.Equal(t, expected.PkgVer, parsed.PkgVer)
			assert.Equal(t, expected.PkgRel, parsed.PkgRel)
			assert.Equal(t, expected.Epoch, parsed.Epoch)
			assert.Equal(t, expected.PkgDesc, parsed.PkgDesc)
			assert.Equal(t, expected.Maintainer, parsed.Maintainer)
			assert.Equal(t, expected.URL, parsed.URL)
			assert.Equal(t, expected.Section, parsed.Section)
			assert.Equal(t, expected.Priority, parsed.Priority)
			assert.Equal(t, expected.Arch, parsed.Arch)
			assert.Equal(t, expected.License, parsed.License)
			assert.Equal(t, expected.Depends, parsed.Depends)
			assert.Equal(t, expected.OptDepends, parsed.OptDepends)
			assert.Equal(t, expected.Suggests, parsed.Suggests)
			assert.Equal(t, expected.Conflicts, parsed.Conflicts)
			assert.Equal(t, expected.Replaces, parsed.Replaces)
			assert.Equal(t, expected.Provides, parsed.Provides)
			assert.Equal(t, expected.Breaks, parsed.Breaks)
			assert.Equal(t, expected.PreDepends, parsed.PreDepends)
			assert.Equal(t, expected.Backup, parsed.Backup)
			assert.Equal(t, expected.Bugs, parsed.Bugs)
			assert.Equal(t, expected.DebTemplate, parsed.DebTemplate)
			assert.Equal(t, expected.DebConfig, parsed.DebConfig)

			norm := normalizeFunctionBody
			assert.Equal(t, norm(expected.PreInst), norm(parsed.PreInst))
			assert.Equal(t, norm(expected.PostInst), norm(parsed.PostInst))
			assert.Equal(t, norm(expected.PreRm), norm(parsed.PreRm))
			assert.Equal(t, norm(expected.PostRm), norm(parsed.PostRm))
			assert.Equal(t, norm(expected.PreTrans), norm(parsed.PreTrans))
			assert.Equal(t, norm(expected.PostTrans), norm(parsed.PostTrans))
			assert.Equal(t, norm(expected.PreUpgrade), norm(parsed.PreUpgrade))
			assert.Equal(t, norm(expected.PostUpgrade), norm(parsed.PostUpgrade))
			assert.Equal(t, norm(expected.Package), norm(parsed.Package))
		})
	}
}

// normalizeFunctionBody strips per-line leading/trailing whitespace and
// trailing blank lines so a raw, unindented string (as ToPKGBUILD builds
// PKGBUILD.Package and the scriptlet fields in memory) compares equal to the
// same content after round-tripping through the PKGBUILD parser's
// pretty-printer, which always re-indents function bodies by two spaces and
// never preserves a trailing blank line before the closing brace.
func normalizeFunctionBody(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, line := range lines {
		lines[i] = strings.TrimSpace(line)
	}

	return strings.Join(lines, "\n")
}

func TestRenderPKGBUILD_ArrayWrapping(t *testing.T) {
	cfg := &nfpm.Config{Info: nfpm.Info{Name: "myapp", Version: "1.0.0"}}
	cfg.Depends = []string{
		"a-fairly-long-dependency-name-one", "a-fairly-long-dependency-name-two",
		"a-fairly-long-dependency-name-three", "a-fairly-long-dependency-name-four",
	}

	data, _, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)

	text := string(data)
	assert.Contains(t, text, "depends=(\n")
	assert.Contains(t, text, "  'a-fairly-long-dependency-name-one'\n")

	for line := range strings.SplitSeq(text, "\n") {
		assert.LessOrEqual(t, len(line), 100, "line too long: %q", line)
	}
}

func TestRenderPKGBUILD_OverrideSuffix(t *testing.T) {
	cfg := &nfpm.Config{
		Info: nfpm.Info{
			Name:    "myapp",
			Version: "1.0.0",
			Overridables: nfpm.Overridables{
				Depends: []string{"glibc"},
			},
		},
		Overrides: map[string]*nfpm.Overridables{
			nfpm.PackagerDeb: {Depends: []string{"libc6"}},
			nfpm.PackagerRPM: {Depends: []string{"glibc"}}, // identical to base: no suffix line expected
		},
	}

	data, _, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)

	text := string(data)
	assert.Contains(t, text, "depends=('glibc')")
	assert.Contains(t, text, "depends__apt=('libc6')")
	assert.NotContains(t, text, "depends__yum")
}

func TestRenderPKGBUILD_DualUpgradeScriptletDiffers(t *testing.T) {
	cfg := renderFixtureConfig()
	cfg.ArchLinux.Scripts.PreUpgrade = "scripts/preupgrade-archlinux.sh"

	data, _, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)

	text := string(data)
	assert.NotContains(t, text, "pre_upgrade() {")
	assert.Contains(t, text, "pre_upgrade__apk() {")
	assert.Contains(t, text, "pre_upgrade__pacman() {")
	assert.Contains(t, text, "render preupgrade\"")
	assert.Contains(t, text, "render preupgrade archlinux\"")
}

func TestRenderPKGBUILD_PkgBaseArchlinuxOverride(t *testing.T) {
	cfg := &nfpm.Config{
		Info: nfpm.Info{
			Name:    "myapp",
			Version: "1.0.0",
			Overridables: nfpm.Overridables{
				ArchLinux: nfpm.ArchLinux{Pkgbase: "mybase"},
			},
		},
	}

	data, _, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)

	text := string(data)
	assert.Contains(t, text, `pkgbase="myapp"`)
	assert.Contains(t, text, `pkgbase__pacman="mybase"`)
}

// TestRenderPKGBUILD_ChangelogWritesSidecar covers acceptance case: a
// changelog with a non-empty OutputDir writes "<name>.changelog" in the
// RPM %changelog dialect and the PKGBUILD carries the matching directive.
func TestRenderPKGBUILD_ChangelogWritesSidecar(t *testing.T) {
	cfg := &nfpm.Config{
		Info: nfpm.Info{Name: "examplepkg", Version: "1.0.0", Changelog: "changelog.yaml"},
	}
	cfg.SetBaseDir("testdata")

	outDir := t.TempDir()

	data, messages, err := cfg.RenderPKGBUILD(&nfpm.RenderOptions{OutputDir: outDir})
	require.NoError(t, err)
	assert.Empty(t, messages)
	assert.Contains(t, string(data), `changelog="examplepkg.changelog"`)

	sidecar, err := os.ReadFile(filepath.Join(outDir, "examplepkg.changelog"))
	require.NoError(t, err)

	headers := rpmChangelogHeaderLines(t, sidecar)
	assert.NotEmpty(t, headers)
	assert.Contains(t, string(sidecar), "- Fix crash on startup\n")
}

// TestRenderPKGBUILD_ChangelogNoOutputDir covers acceptance case: a
// changelog with an empty OutputDir still emits the directive, writes no
// file, and returns exactly one explanatory message.
func TestRenderPKGBUILD_ChangelogNoOutputDir(t *testing.T) {
	cfg := &nfpm.Config{
		Info: nfpm.Info{Name: "examplepkg", Version: "1.0.0", Changelog: "changelog.yaml"},
	}
	cfg.SetBaseDir("testdata")

	data, messages, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)
	assert.Contains(t, string(data), `changelog="examplepkg.changelog"`)
	require.Len(t, messages, 1)
	assert.Contains(t, messages[0], "examplepkg.changelog")
}

// TestRenderPKGBUILD_NoChangelog covers acceptance case: no changelog set
// emits no changelog= directive and no message.
func TestRenderPKGBUILD_NoChangelog(t *testing.T) {
	cfg := &nfpm.Config{Info: nfpm.Info{Name: "myapp", Version: "1.0.0"}}

	data, messages, err := cfg.RenderPKGBUILD(nil)
	require.NoError(t, err)
	assert.NotContains(t, string(data), "changelog=")
	assert.Empty(t, messages)
}

// TestRenderPKGBUILD_ChangelogUnreadableIsHardError covers acceptance case:
// a changelog: path that cannot be loaded is a hard, typed error.
func TestRenderPKGBUILD_ChangelogUnreadableIsHardError(t *testing.T) {
	cfg := &nfpm.Config{
		Info: nfpm.Info{Name: "myapp", Version: "1.0.0", Changelog: "does-not-exist.yaml"},
	}
	cfg.SetBaseDir("testdata")

	_, _, err := cfg.RenderPKGBUILD(nil)
	require.Error(t, err)

	var yerr *yaperrors.YapError
	require.True(t, errors.As(err, &yerr))
	assert.Equal(t, yaperrors.ErrTypeFileSystem, yerr.Type)
}
