package nfpm

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/M0Rf30/yap/v2/pkg/buildinfo"
	"github.com/M0Rf30/yap/v2/pkg/errors"
	"github.com/M0Rf30/yap/v2/pkg/i18n"
)

// RenderYAML marshals c as a canonical nfpm.yaml document: 2-space indent,
// deterministic key order (the Go struct field order), prefixed by a
// provenance comment. The output round-trips through Parse for any Config
// produced by FromPKGBUILD.
func (c *Config) RenderYAML() ([]byte, error) {
	var body bytes.Buffer

	enc := yaml.NewEncoder(&body)
	enc.SetIndent(2)

	if err := enc.Encode(c); err != nil {
		return nil, errors.Wrap(err, errors.ErrTypeInternal, i18n.T("errors.nfpm.render_yaml_failed")).
			WithOperation("RenderYAML")
	}

	if err := enc.Close(); err != nil {
		return nil, errors.Wrap(err, errors.ErrTypeInternal, i18n.T("errors.nfpm.render_yaml_failed")).
			WithOperation("RenderYAML")
	}

	header := fmt.Sprintf("# Generated by yap %s from PKGBUILD\n", buildinfo.Version)

	return append([]byte(header), body.Bytes()...), nil
}
