# Dependabot configuration for YAP
# Documentation: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically

version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "M0Rf30"
    assignees:
      - "M0Rf30"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"

  # Go module dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "M0Rf30"
    assignees:
      - "M0Rf30"
    labels:
      - "dependencies"
      - "go"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
      include: "scope"
    groups:
      # Group patch updates for better management
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
      # Group minor updates
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
    ignore:
      # Ignore specific packages that may cause issues
      - dependency-name: "golang.org/x/sys"
        update-types: ["version-update:semver-major"]
      - dependency-name: "golang.org/x/net"
        update-types: ["version-update:semver-major"]
      # Example: Ignore major version updates for specific critical dependencies
      # - dependency-name: "github.com/spf13/cobra"
      #   update-types: ["version-update:semver-major"]

  # Docker dependencies (if Dockerfiles contain FROM instructions)
  - package-ecosystem: "docker"
    directory: "/build/deploy"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "M0Rf30"
    assignees:
      - "M0Rf30"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
