version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - predeclared
    - revive
    - staticcheck
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wsl_v5

  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - mnd
    - wrapcheck

  settings:
    cyclop:
      max-complexity: 15

    dupl:
      threshold: 80

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - paramTypeCombine
        - whyNoLint

    gocyclo:
      min-complexity: 15

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G204 # Subprocess with variable
        - G301 # Poor file permissions
        - G302 # Poor file permissions

    lll:
      line-length: 120

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: superfluous-else
        - name: var-naming

    staticcheck:
      checks:
        - all

  exclusions:
    generated: strict

    rules:
      # Project-specific: Allow generic package names in builders/common
      - path: "pkg/builders/common/"
        text: "avoid meaningless package names"
        linters:
          - revive

      # Allow custom errors package name (conflicts with stdlib but is intentional)
      - path: "pkg/errors/"
        text: "avoid package names that conflict with Go standard library"
        linters:
          - revive

      # Allow custom crypto package name (conflicts with stdlib but is intentional)
      - path: "pkg/crypto/"
        text: "avoid package names that conflict with Go standard library"
        linters:
          - revive

      # Skip all linting for documentation and distribution directories
      - path: "(docs|dist|bin|examples)/"
        linters:
          - asciicheck
          - bodyclose
          - copyloopvar
          - cyclop
          - dupl
          - durationcheck
          - errcheck
          - errorlint
          - gochecknoinits
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - misspell
          - nakedret
          - nestif
          - nilerr
          - nilnil
          - noctx
          - predeclared
          - revive
          - staticcheck
          - testpackage
          - thelper
          - unconvert
          - unparam
          - unused
          - wastedassign
          - whitespace

      # Skip all linting for protobuf generated files
      - path: ".*\\.pb\\.go$"
        linters:
          - asciicheck
          - bodyclose
          - copyloopvar
          - cyclop
          - dupl
          - durationcheck
          - errcheck
          - errorlint
          - gochecknoinits
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - misspell
          - nakedret
          - nestif
          - nilerr
          - nilnil
          - noctx
          - predeclared
          - revive
          - staticcheck
          - testpackage
          - thelper
          - unconvert
          - unparam
          - unused
          - wastedassign
          - whitespace

      # Skip all linting for other generated files
      - path: ".*_generated\\.go$"
        linters:
          - asciicheck
          - bodyclose
          - copyloopvar
          - cyclop
          - dupl
          - durationcheck
          - errcheck
          - errorlint
          - gochecknoinits
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - misspell
          - nakedret
          - nestif
          - nilerr
          - nilnil
          - noctx
          - predeclared
          - revive
          - staticcheck
          - testpackage
          - thelper
          - unconvert
          - unparam
          - unused
          - wastedassign
          - whitespace

      # Relax certain rules for test files
      - path: "_test\\.go"
        linters:
          - cyclop
          - dupl
          - goconst
          - gocyclo
          - gosec
          - lll

      # Allow poor file permissions in tests
      - path: "_test\\.go"
        text: "G30[12]:"
        linters:
          - gosec

      # Allow internal test packages for testing unexported functions
      # Many tests need to test internal implementation details and require package-level access
      - path: "(cmd/yap/command|pkg/(builders|constants|core|crypto|download|files|git|graph|logger|packer|pkgbuild|platform|project|set|shell))/.*_test\\.go"
        text: "package should be `.*_test` instead of"
        linters:
          - testpackage

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/M0Rf30/yap

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
