version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - ginkgolinter
    - gochecknoinits
    - gosec
    - importas
    - misspell
    - nakedret
    - nolintlint
    - revive
    - testifylint
    - unconvert
    - unparam
    - wastedassign
    - wsl_v5
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - ireturn
    - mnd
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G401 # Weak cryptographic primitive - justified for APK format compatibility
        - G304 # File path provided as taint input - controlled within package build process
    revive:
      rules:
        - name: dot-imports
          disabled: true
        - name: filename-format
          arguments:
            - ^[a-z][_a-z0-9]*.go$
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -SA1019
    testifylint:
      enable-all: true
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/M0Rf30/yap)
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/M0Rf30/yap
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
