version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - errorlint
    - nilerr
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    - gochecknoinits
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - predeclared
    - cyclop
    - gocyclo
    - goconst
    - gocritic
    - dupl
    - nestif
    - lll

  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gomoddirectives
    - mnd
    - wrapcheck
    - wsl_v5

  settings:
    cyclop:
      max-complexity: 15

    dupl:
      threshold: 80

    goconst:
      min-len: 3
      min-occurrences: 3

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - paramTypeCombine
        - whyNoLint

    gocyclo:
      min-complexity: 15

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G204
        - G301
        - G302

    lll:
      line-length: 100

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else

    staticcheck:
      checks:
        - all

  exclusions:
    generated: strict

    rules:
      - path: "(docs|dist|bin)/"
        linters:
          - gosec
          - govet
          - staticcheck
          - unused
          - errcheck
          - ineffassign
          - revive
          - gocritic
          - dupl
          - goconst
          - cyclop
          - gocyclo
          - lll
          - nestif
          - asciicheck
          - bodyclose
          - copyloopvar
          - durationcheck
          - gochecknoinits
          - misspell
          - nakedret
          - unconvert
          - unparam
          - wastedassign
          - whitespace
          - predeclared
          - errorlint
          - nilerr

      - path: ".*\\.pb\\.go$"
        linters:
          - gosec
          - govet
          - staticcheck
          - unused
          - errcheck
          - ineffassign
          - revive
          - gocritic
          - dupl
          - goconst
          - cyclop
          - gocyclo
          - lll
          - nestif
          - asciicheck
          - bodyclose
          - copyloopvar
          - durationcheck
          - gochecknoinits
          - misspell
          - nakedret
          - unconvert
          - unparam
          - wastedassign
          - whitespace
          - predeclared
          - errorlint
          - nilerr

      - path: ".*_generated\\.go$"
        linters:
          - gosec
          - govet
          - staticcheck
          - unused
          - errcheck
          - ineffassign
          - revive
          - gocritic
          - dupl
          - goconst
          - cyclop
          - gocyclo
          - lll
          - nestif
          - asciicheck
          - bodyclose
          - copyloopvar
          - durationcheck
          - gochecknoinits
          - misspell
          - nakedret
          - unconvert
          - unparam
          - wastedassign
          - whitespace
          - predeclared
          - errorlint
          - nilerr

      - path: "_test\\.go"
        linters:
          - gosec
          - dupl
          - goconst
          - lll
          - cyclop
          - gocyclo

      - path: "_test\\.go"
        text: "G30[12]:"
        linters:
          - gosec

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/M0Rf30/yap

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
