# Options for analysis running.
linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
  disable:
    # here some dropped deprecated checks
    # reduce warning messages
    - deadcode
    - exhaustivestruct
    - golint
    - gocritic
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - structcheck
    - varcheck
    - wastedassign
    # here some custom dropped checks temporary disabled
    # they will be enabled
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
    - gomnd
    - ireturn
    - typecheck
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
