// Package apk provides Alpine Linux package building functionality and constants.
package apk

// dotPkginfo is the template for APK .PKGINFO metadata file.
// APK packages use a simpler format compared to Pacman.
// Reference: https://wiki.alpinelinux.org/wiki/Apk_spec
const dotPkginfo = `# Generated by yap {{.YAPVersion}}
pkgname = {{.PkgName}}
pkgver = {{if .Epoch}}{{.Epoch}}:{{end}}{{.PkgVer}}-r{{.PkgRel}}
pkgdesc = {{.PkgDesc}}
url = {{.URL}}
builddate = {{.BuildDate}}
{{- if .Maintainer}}
packager = {{.Maintainer}}
{{- end }}
size = {{.InstalledSize}}
arch = {{.ArchComputed}}
{{- if .Origin}}
origin = {{.Origin}}
{{- end }}
{{- if .Commit}}
commit = {{.Commit}}
{{- end }}
{{- if .License}}
{{ range .License }}license = {{ . }}
{{ end }}
{{- end }}
{{- if .Replaces}}
{{ range .Replaces }}replaces = {{ . }}
{{ end }}
{{- end }}
{{- if .Provides}}
{{ range .Provides }}provides = {{ . }}
{{ end }}
{{- end }}
{{- if .Depends}}
{{ range .Depends }}depend = {{ . }}
{{ end }}
{{- end }}
{{- if .DataHash}}
datahash = {{.DataHash}}
{{- end }}
`

// installScript is the template for APK install scripts.
// APK uses shell scripts with specific function names for lifecycle hooks.
const installScript = `#!/bin/sh
{{- if .PreInst}}

pre_install() {
{{.PreInst}}
}
{{- end }}

{{- if .PostInst}}

post_install() {
{{.PostInst}}
}
{{- end }}

{{- if .PreInst}}

pre_upgrade() {
{{.PreInst}}
}
{{- end }}

{{- if .PostInst}}

post_upgrade() {
{{.PostInst}}
}
{{- end }}

{{- if .PreRm}}

pre_deinstall() {
{{.PreRm}}
}
{{- end }}

{{- if .PostRm}}

post_deinstall() {
{{.PostRm}}
}
{{- end }}
`
