// Command mcp-surface introspects the live yap-mcp server and writes an
// authoritative inventory of its tools, prompts, and resources to
// docs/mcp-surface.md. It is the source of truth for the SKILL card and the
// AGENTS.md "MCP surface" section — run it via `go generate ./pkg/mcp/...`
// (or `go run ./cmd/mcp-surface`) whenever the tool surface changes.
//
// Because it connects to the real NewServer() over an in-memory transport,
// the generated doc can never disagree with what clients actually see.
package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	mcpsdk "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/M0Rf30/yap/v2/pkg/errors"
	yapmcp "github.com/M0Rf30/yap/v2/pkg/mcp"
)

// moduleRoot walks up from the current working directory to the directory
// containing go.mod, so the output path is stable whether invoked from the
// repo root (`go run ./cmd/mcp-surface`) or from pkg/mcp (`go generate`).
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, statErr := os.Stat(filepath.Join(dir, "go.mod")); statErr == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New(errors.ErrTypeFileSystem,
				"go.mod not found above "+dir)
		}

		dir = parent
	}
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "mcp-surface:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := moduleRoot()
	if err != nil {
		return err
	}

	outPath := filepath.Join(root, "docs", "mcp-surface.md")

	ctx := context.Background()
	srv := yapmcp.NewServer()
	client := mcpsdk.NewClient(&mcpsdk.Implementation{Name: "mcp-surface", Version: "0"}, nil)

	srvT, clientT := mcpsdk.NewInMemoryTransports()

	srvSess, err := srv.Connect(ctx, srvT, nil)
	if err != nil {
		return errors.Wrap(err, errors.ErrTypeInternal, "server connect")
	}
	defer func() { _ = srvSess.Close() }()

	cs, err := client.Connect(ctx, clientT, nil)
	if err != nil {
		return errors.Wrap(err, errors.ErrTypeInternal, "client connect")
	}
	defer func() { _ = cs.Close() }()

	var b strings.Builder

	b.WriteString("# yap-mcp surface (generated)\n\n")
	b.WriteString("<!-- GENERATED by `go run ./cmd/mcp-surface` — DO NOT EDIT BY HAND. -->\n")
	b.WriteString("<!-- Run `go generate ./pkg/mcp/...` after changing the tool surface. -->\n\n")

	if err := writeTools(ctx, cs, &b); err != nil {
		return err
	}

	lp, err := cs.ListPrompts(ctx, &mcpsdk.ListPromptsParams{})
	if err != nil {
		return errors.Wrap(err, errors.ErrTypeInternal, "ListPrompts")
	}

	promptRows := make([]twoColRow, 0, len(lp.Prompts))
	for _, p := range lp.Prompts {
		promptRows = append(promptRows, twoColRow{key: p.Name, desc: p.Description})
	}

	writeTwoColSection(&b, "Prompts", "Prompt", promptRows)

	lr, err := cs.ListResources(ctx, &mcpsdk.ListResourcesParams{})
	if err != nil {
		return errors.Wrap(err, errors.ErrTypeInternal, "ListResources")
	}

	resourceRows := make([]twoColRow, 0, len(lr.Resources))
	for _, r := range lr.Resources {
		resourceRows = append(resourceRows, twoColRow{key: r.URI, desc: r.Description})
	}

	writeTwoColSection(&b, "Resources", "URI", resourceRows)

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return errors.Wrap(err, errors.ErrTypeFileSystem, "mkdir docs")
	}

	if err := os.WriteFile(outPath, []byte(b.String()), 0o600); err != nil {
		return errors.Wrap(err, errors.ErrTypeFileSystem, "write "+outPath)
	}

	fmt.Println("wrote", outPath)

	return nil
}

func annotationTags(a *mcpsdk.ToolAnnotations) string {
	if a == nil {
		return ""
	}

	var tags []string
	if a.ReadOnlyHint {
		tags = append(tags, "read-only")
	}

	if a.IdempotentHint {
		tags = append(tags, "idempotent")
	}

	if a.DestructiveHint != nil && *a.DestructiveHint {
		tags = append(tags, "destructive")
	}

	if a.OpenWorldHint != nil && *a.OpenWorldHint {
		tags = append(tags, "open-world")
	}

	return strings.Join(tags, ", ")
}

func writeTools(ctx context.Context, cs *mcpsdk.ClientSession, b *strings.Builder) error {
	lt, err := cs.ListTools(ctx, &mcpsdk.ListToolsParams{})
	if err != nil {
		return errors.Wrap(err, errors.ErrTypeInternal, "ListTools")
	}

	tools := lt.Tools
	sort.Slice(tools, func(i, j int) bool { return tools[i].Name < tools[j].Name })

	fmt.Fprintf(b, "## Tools (%d)\n\n", len(tools))
	b.WriteString("| Tool | Annotations | Description |\n")
	b.WriteString("| ---- | ----------- | ----------- |\n")

	for _, t := range tools {
		desc := strings.ReplaceAll(t.Description, "\n", " ")
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", t.Name, annotationTags(t.Annotations), desc)
	}

	b.WriteString("\n")

	return nil
}

// twoColRow is one (key, description) pair for a simple two-column section.
type twoColRow struct {
	key  string
	desc string
}

// writeTwoColSection renders a sorted "## <title> (N)" table with a key column
// and a description column. Shared by the prompts and resources sections.
func writeTwoColSection(b *strings.Builder, title, keyHeader string, rows []twoColRow) {
	sort.Slice(rows, func(i, j int) bool { return rows[i].key < rows[j].key })

	fmt.Fprintf(b, "## %s (%d)\n\n", title, len(rows))
	fmt.Fprintf(b, "| %s | Description |\n", keyHeader)
	b.WriteString("| --- | ----------- |\n")

	for _, r := range rows {
		fmt.Fprintf(b, "| `%s` | %s |\n", r.key, strings.ReplaceAll(r.desc, "\n", " "))
	}

	b.WriteString("\n")
}
