// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package yapdbgen

type Cap struct {
	PackageID int64
	Kind      string
	Name      string
	Flags     int64
	Version   string
}

type File struct {
	PackageID  int64
	Path       string
	Mode       int64
	IsDir      int64
	IsSymlink  int64
	LinkTarget string
	Sha256     string
}

type Meta struct {
	Key   string
	Value string
}

type Package struct {
	ID          int64
	Name        string
	Epoch       string
	Version     string
	Release     string
	Arch        string
	Format      string
	InstallTime int64
	Summary     string
}
