// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package yapdbgen

import (
	"context"
)

const capsByPackage = `-- name: CapsByPackage :many
SELECT kind, name, flags, version
FROM caps
WHERE package_id = ?
ORDER BY kind ASC, name ASC
`

type CapsByPackageRow struct {
	Kind    string
	Name    string
	Flags   int64
	Version string
}

// Get all capabilities for a package.
func (q *Queries) CapsByPackage(ctx context.Context, packageID int64) ([]CapsByPackageRow, error) {
	rows, err := q.db.QueryContext(ctx, capsByPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapsByPackageRow{}
	for rows.Next() {
		var i CapsByPackageRow
		if err := rows.Scan(
			&i.Kind,
			&i.Name,
			&i.Flags,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPackages = `-- name: CountPackages :one
SELECT COUNT(*) FROM packages
`

// Count total installed packages.
func (q *Queries) CountPackages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPackages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePackageByNameArch = `-- name: DeletePackageByNameArch :exec
DELETE FROM packages WHERE name = ? AND arch = ?
`

type DeletePackageByNameArchParams struct {
	Name string
	Arch string
}

// Delete a package by name and arch (cascades to files and caps).
func (q *Queries) DeletePackageByNameArch(ctx context.Context, arg DeletePackageByNameArchParams) error {
	_, err := q.db.ExecContext(ctx, deletePackageByNameArch, arg.Name, arg.Arch)
	return err
}

const filesByPackage = `-- name: FilesByPackage :many
SELECT package_id, path, mode, is_dir, is_symlink, link_target, sha256
FROM files
WHERE package_id = ?
ORDER BY path ASC
`

// Get all files for a package.
func (q *Queries) FilesByPackage(ctx context.Context, packageID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, filesByPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.PackageID,
			&i.Path,
			&i.Mode,
			&i.IsDir,
			&i.IsSymlink,
			&i.LinkTarget,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCap = `-- name: InsertCap :exec
INSERT INTO caps (package_id, kind, name, flags, version)
VALUES (?, ?, ?, ?, ?)
`

type InsertCapParams struct {
	PackageID int64
	Kind      string
	Name      string
	Flags     int64
	Version   string
}

// Insert a capability record.
func (q *Queries) InsertCap(ctx context.Context, arg InsertCapParams) error {
	_, err := q.db.ExecContext(ctx, insertCap,
		arg.PackageID,
		arg.Kind,
		arg.Name,
		arg.Flags,
		arg.Version,
	)
	return err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO files (package_id, path, mode, is_dir, is_symlink, link_target, sha256)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertFileParams struct {
	PackageID  int64
	Path       string
	Mode       int64
	IsDir      int64
	IsSymlink  int64
	LinkTarget string
	Sha256     string
}

// Insert a file record for a package.
func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.ExecContext(ctx, insertFile,
		arg.PackageID,
		arg.Path,
		arg.Mode,
		arg.IsDir,
		arg.IsSymlink,
		arg.LinkTarget,
		arg.Sha256,
	)
	return err
}

const insertPackage = `-- name: InsertPackage :one
INSERT INTO packages (name, epoch, version, release, arch, format, install_time, summary)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id
`

type InsertPackageParams struct {
	Name        string
	Epoch       string
	Version     string
	Release     string
	Arch        string
	Format      string
	InstallTime int64
	Summary     string
}

// Insert a new package record.
func (q *Queries) InsertPackage(ctx context.Context, arg InsertPackageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPackage,
		arg.Name,
		arg.Epoch,
		arg.Version,
		arg.Release,
		arg.Arch,
		arg.Format,
		arg.InstallTime,
		arg.Summary,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const isInstalledByName = `-- name: IsInstalledByName :one
SELECT EXISTS(SELECT 1 FROM packages WHERE name = ?)
`

// Check if a package is installed by name.
func (q *Queries) IsInstalledByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isInstalledByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPackages = `-- name: ListPackages :many
SELECT id, name, epoch, version, release, arch, format, install_time, summary
FROM packages
ORDER BY name ASC
`

// List all installed packages (without files/caps).
func (q *Queries) ListPackages(ctx context.Context) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Epoch,
			&i.Version,
			&i.Release,
			&i.Arch,
			&i.Format,
			&i.InstallTime,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupPackageByNameArch = `-- name: LookupPackageByNameArch :one
SELECT id, name, epoch, version, release, arch, format, install_time, summary
FROM packages
WHERE name = ? AND arch = ?
`

type LookupPackageByNameArchParams struct {
	Name string
	Arch string
}

// Look up a package by name and arch.
func (q *Queries) LookupPackageByNameArch(ctx context.Context, arg LookupPackageByNameArchParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, lookupPackageByNameArch, arg.Name, arg.Arch)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Epoch,
		&i.Version,
		&i.Release,
		&i.Arch,
		&i.Format,
		&i.InstallTime,
		&i.Summary,
	)
	return i, err
}

const lookupProviders = `-- name: LookupProviders :many
SELECT DISTINCT p.id, p.name, p.epoch, p.version, p.release, p.arch, p.format, p.install_time, p.summary
FROM packages p
JOIN caps c ON p.id = c.package_id
WHERE c.kind = 'provide' AND c.name = ?
ORDER BY p.name ASC
`

// Find all packages that provide a capability.
func (q *Queries) LookupProviders(ctx context.Context, name string) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, lookupProviders, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Package{}
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Epoch,
			&i.Version,
			&i.Release,
			&i.Arch,
			&i.Format,
			&i.InstallTime,
			&i.Summary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
