// Package constants defines global constants and configuration values used throughout YAP.
package constants

import (
	"fmt"
	"runtime"
	"strings"

	"github.com/M0Rf30/yap/v2/pkg/buildinfo"
	"github.com/M0Rf30/yap/v2/pkg/set"
)

const (
	// DockerOrg defines the Docker organization prefix for YAP containers.
	DockerOrg = "docker.io/m0rf30/yap-"
	// Git defines the git command name.
	Git = "git"
	// goVersion defines the Go toolchain version to download.
	goVersion = "1.26.1"
)

// YAPVersion defines the current version of YAP. It mirrors the ldflags-injected
// buildinfo.Version so generated metadata (.PKGINFO "Generated by yap ...")
// reflects the real build version instead of a hardcoded fallback.
var YAPVersion = buildinfo.Version

// GoArchiveURL returns the Go archive download URL for the current architecture.
func GoArchiveURL() string {
	return fmt.Sprintf("https://go.dev/dl/go%s.linux-%s.tar.gz", goVersion, runtime.GOARCH)
}

var (
	// Releases contains the supported Linux distribution IDs as defined in /etc/os-release.
	// These values are not invented, but refer to /etc/os-release ID field values.
	Releases = [...]string{
		DistroAlmalinux,
		DistroAlpine,
		DistroAmzn,
		DistroArch,
		DistroCentos,
		DistroDebian,
		DistroFedora,
		DistroLinuxmint,
		DistroOpenSUSELeap,
		DistroOpenSUSETumbleweed,
		DistroOl,
		DistroPop,
		DistroRhel,
		DistroRocky,
		DistroUbuntu,
	}

	// DistroToPackageManager maps distribution names to their package managers.
	DistroToPackageManager = map[string]string{
		DistroAlmalinux:          PMYum,
		DistroAlpine:             PMApk,
		DistroAmzn:               PMYum,
		DistroArch:               PMPacman,
		DistroCentos:             PMYum,
		DistroDebian:             PMApt,
		DistroFedora:             PMYum,
		DistroLinuxmint:          PMApt,
		DistroOl:                 PMYum,
		DistroOpenSUSELeap:       PMZypper,
		DistroOpenSUSETumbleweed: PMZypper,
		DistroPop:                PMApt,
		DistroRhel:               PMYum,
		DistroRocky:              PMYum,
		DistroUbuntu:             PMApt,
	}

	// Packers defines the supported package managers for different distributions.
	Packers = [...]string{
		PMApk,
		PMApt,
		PMPacman,
		PMYum,
		PMZypper,
	}

	// Distros contains the list of supported distribution names.
	Distros = []string{}
	// DistrosSet contains the set of supported distributions.
	DistrosSet = set.NewSet()
	// DistroPackageManager maps distributions to their package managers.
	DistroPackageManager = map[string]string{}
	// PackagersSet contains the set of supported package managers.
	PackagersSet = set.NewSet()
)

// init initializes the package.
//
// It iterates over the Releases slice and adds each release to the ReleasesSet set.
// It also extracts the distribution name from each release and adds it to the Distros slice.
// The function then iterates over the Distros slice and assigns the corresponding package manager
// to each distribution in the DistroPackageManager map.
// If a distribution does not have a supported package manager, the function prints an error message
// and exits the program.
// Finally, it adds each package manager to the PackagersSet set.
//
//nolint:gochecknoinits // Required for initialization of package constants and data structures
func init() {
	for _, release := range &Releases {
		distro := strings.Split(release, "_")[0]
		Distros = append(Distros, distro)
		DistrosSet.Add(distro)
	}

	for _, distro := range Distros {
		DistroPackageManager[distro] = DistroToPackageManager[distro]
	}

	for _, packageManager := range Packers {
		PackagersSet.Add(packageManager)
	}
}
