package pacman

import (
	"bytes"
	"strings"
	"testing"
)

func TestDotBuildinfoTemplate(t *testing.T) {
	if dotBuildinfo == "" {
		t.Error("dotBuildinfo template is empty")
	}

	requiredFields := []string{
		"format = 2",
		"pkgname = {{.PkgName}}",
		"pkgver = ",
		"buildtool = yap",
	}

	for _, field := range requiredFields {
		if !strings.Contains(dotBuildinfo, field) {
			t.Errorf("dotBuildinfo template missing field: %s", field)
		}
	}
}

func TestDotPkginfoTemplate(t *testing.T) {
	if dotPkginfo == "" {
		t.Error("dotPkginfo template is empty")
	}

	requiredFields := []string{
		"pkgname = {{.PkgName}}",
		"pkgver = ",
		"pkgdesc = {{.PkgDesc}}",
		"size = {{.InstalledSize}}",
		"arch = {{.ArchComputed}}",
	}

	for _, field := range requiredFields {
		if !strings.Contains(dotPkginfo, field) {
			t.Errorf("dotPkginfo template missing field: %s", field)
		}
	}

	if !strings.Contains(dotPkginfo, "Generated by yap") {
		t.Error("dotPkginfo should contain yap attribution")
	}
}

func TestDotPkginfoTemplateRendersGroup(t *testing.T) {
	pkgBuild := createTestPKGBUILD()
	pkgBuild.Group = "Applications/Internet"

	tmpl := pkgBuild.RenderSpec(dotPkginfo)

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkgBuild); err != nil {
		t.Fatalf("rendering dotPkginfo with a non-empty Group must not error: %v", err)
	}

	output := buf.String()

	groupLines := 0

	for line := range strings.SplitSeq(output, "\n") {
		if strings.HasPrefix(line, "group = ") {
			groupLines++
		}
	}

	if groupLines != 1 {
		t.Errorf("expected exactly one 'group = ' line, got %d in:\n%s", groupLines, output)
	}

	if !strings.Contains(output, "group = Applications/Internet") {
		t.Errorf("expected output to contain 'group = Applications/Internet', got:\n%s", output)
	}
}

func TestDotMtreeTemplate(t *testing.T) {
	if dotMtree == "" {
		t.Error("dotMtree template is empty")
	}

	requiredElements := []string{
		"#mtree",
		"/set type=file uid=0 gid=0 mode=644",
		"{{- range . }}",
		"{{- if eq .Type \"dir\" }}",
		"{{- else if eq .Type \"symlink\" }}",
	}

	for _, element := range requiredElements {
		if !strings.Contains(dotMtree, element) {
			t.Errorf("dotMtree template missing element: %s", element)
		}
	}
}

func TestPostInstallTemplate(t *testing.T) {
	if postInstall == "" {
		t.Error("postInstall template is empty")
	}

	requiredHooks := []string{
		"pre_install()", "post_install()", "pre_upgrade()", "post_upgrade()",
		"pre_remove()", "post_remove()",
	}

	for _, hook := range requiredHooks {
		if !strings.Contains(postInstall, hook) {
			t.Errorf("postInstall template missing hook: %s", hook)
		}
	}
}

func TestSpecFileTemplate(t *testing.T) {
	if specFile == "" {
		t.Error("specFile template is empty")
	}

	requiredFields := []string{
		"pkgname={{.PkgName}}",
		"pkgver={{.PkgVer}}",
		"pkgrel={{.PkgRel}}",
		"pkgdesc=\"{{.PkgDesc}}\"",
		"package() {",
	}

	for _, field := range requiredFields {
		if !strings.Contains(specFile, field) {
			t.Errorf("specFile template missing field: %s", field)
		}
	}
}

func TestTemplateConsistency(t *testing.T) {
	templates := map[string]string{
		"dotBuildinfo": dotBuildinfo,
		"dotPkginfo":   dotPkginfo,
		"dotMtree":     dotMtree,
		"postInstall":  postInstall,
		"specFile":     specFile,
	}

	for name, template := range templates {
		if template == "" {
			t.Errorf("Template %s is empty", name)
		}
	}
}
