name: docker images

on:
  push:
    branches:
      - main
jobs:
  distro_matrix:
    strategy:
      matrix:
        os: [alpine, rocky-8, rocky-9, ubuntu-focal, ubuntu-jammy, ubuntu-noble]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: m0rf30/yap*
          labels: |
            maintainer=Yap
            org.opencontainers.image.authors=M0Rf30
            org.opencontainers.image.title=yap
            org.opencontainers.image.description=Package software with ease 📦
            org.opencontainers.image.vendor=M0Rf30
          tags: |
            type=raw,value=latest

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-${{ matrix.os }}:latest
          file: build/deploy/${{ matrix.os }}/Dockerfile
