name: Docker Image CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: m0rf30/yap*
          labels: |
            maintainer=Yap
            org.opencontainers.image.authors=M0Rf30
            org.opencontainers.image.title=yap
            org.opencontainers.image.description=Package software with ease 📦
            org.opencontainers.image.vendor=M0Rf30
          tags: |
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-alpine:latest
          file: docker/alpine/Dockerfile

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     labels: ${{ steps.meta.outputs.labels }}
      #     tags: |
      #       m0rf30/yap-arch:latest
      #       ghcr.io/m0rf30/yap-arch:latest
      #     file: docker/arch/Dockerfile

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     labels: ${{ steps.meta.outputs.labels }}
      #     tags: |
      #       m0rf30/yap-opensuse-tubleweed:latest
      #       ghcr.io/m0rf30/yap-opensuse-tubleweed:latest
      #     file: docker/opensuse-tubleweed/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-rocky-8:latest
          file: docker/rocky-8/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-rocky-9:latest
          file: docker/rocky-9/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-ubuntu-focal:latest
          file: docker/ubuntu-focal/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-ubuntu-jammy:latest
          file: docker/ubuntu-jammy/Dockerfile
