name: gosec

on:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run gosec
        uses: securego/gosec@master
        with:
          args: ./...
