# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write

jobs:
  distro_matrix:
    strategy:
      matrix:
        os: [alpine, rocky-8, rocky-9, ubuntu-focal, ubuntu-jammy]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: m0rf30/yap*
          labels: |
            maintainer=Yap
            org.opencontainers.image.authors=M0Rf30
            org.opencontainers.image.title=yap
            org.opencontainers.image.description=Package software with ease 📦
            org.opencontainers.image.vendor=M0Rf30
          tags: |
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            m0rf30/yap-${{ matrix.os }}:${{ steps.meta.outputs.tags }}
          file: build/deploy/${{ matrix.os }}/Dockerfile
